fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
         address: "gerasymov.m@gmail.com"
         sender_name: "Admin"
    registration:
         form:
            type: App\Form\RegistrationType